end_conversation: No problem, have a great day!
rephrase: Sorry to hear that. I'm still learning. Could you maybe try rephrasing your request?
did_not_understand: Sorry, I did not understand '%s'. Could you maybe rephrase?
anything_else: Is there anything else I can help you with?

care_intro:
  line_1: Hello 👋
  line_2: I'm the virtual advisor for Newcastle City Council's adult care and services.
  line_3: At the moment, I can help you with information and advice about your equipment needs and options on how to get equipment.
  for_you: But before we move on, are you enquiring for yourself or someone else?
  you_live_in_newcastle: Do you live in Newcastle?
  someone_else_live_in_newcastle: Does the person live in Newcastle?
  external_council: I am only able to advise residents of Newcastle because all my advice is local to the area. You can find your local council at https://www.gov.uk/find-local-council
  check_council: Well, you can always check. I'll give you a link so that you can find your council. https://www.gov.uk/find-local-council
  help_intro: |
    Great!
     
    I can help you with:
      
    * general advice about equipment
    * finding specific types of equipment
    * getting and paying for equipment
    * council support advice

    What would you like help with?
    (For example, trouble getting in and out of bed, shower equipment...)
  
help_chooser:
  options: Sorry, I quite work out what you want. Please choose from the following options.
  confirm:
    equipment: OK, I can see you need help with an equipment request, is that right?
    getting_equipment: OK, I can see you need help with paying for care, is that right?

equipment:
  for_you: Is this for you or someone else?
  you_live_in_newcastle: Do you live in Newcastle?
  someone_else_live_in_newcastle: Does the person live in Newcastle?
  kind_of_help: What kind of help do you need? For example, do you need help with bathing or eating, or do you have an audio or visual impairment?
  what_you_were_looking_for: Was that what you were looking for?
  move_to_getting: Great! Glad I could help. Are you interested in finding about how you can get this equipment?
  anything_else: OK. Is there anything else I can help you with?
  confirm: It looks like you're looking for help with equipment %s, is that right?
  message: OK, I've found some information on equipment that can help you %s:"
  bathroom:
    name: in the bathroom
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Bathroom"
  bedroom:
    name: in the bedroom
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Bedroom"
  diningroom:
    name: in the dining room
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/DiningRoom"
  garden:
    name: in the garden
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Garden"
  office:
    name: in the office
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Office"
  kitchen:
    name: in the kitchen
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Kitchen"
  lounge:
    name: in the lounge
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Lounge"
  stairs:
    name: on the stairs
    link: "https://www.myequipmentnewcastle.org.uk/catalogue/Stairs"

getting_equipment:
  info: |
    Getting equipment yourself is often quicker than waiting for council support.  There are a lot of resources out there that can help with access to equipment, like equipment loan services, grants and advice.
    Did you know that a lot of shops like Amazon, Argos and Boots sell equipment too! It’s easy to ask in the store or search online, but it’s always good to speak with someone for advice on what to buy.
    Newcastle City Council can often help with payment and access to certain equipment.
  self_or_council: What would you like to learn more about?
  choices:
    - Access myself
    - Council support
  access_myself: |
    Here are some useful resources that may help you with getting and paying equipment yourself:
      * https://www.moneyadviceservice.org.uk/en/articles/shopping-around-for-disability-aids-and-equipment
      * http://www.disabilitynorth.org.uk/
  council_support: |
    The council offers support with equipment ...
  assessment: Would you like to find out more about applying for an assessment?

assessment:
  intro: Great! We need to collect a few pieces of information so that we can pass it onto the Social Care Direct team to followup on your request for assessing payment support available to you.
  first_name: What is your first name?
  surname: What is your surname?
  phone_number: Phone number we can use to contact you?
  info: Thank you. Here's the information you've provided
  confirm: Just to confirm, is this information correct?
  thank_you: Thank you for answering my questions. I have now passed them to the Social Care Direct team.
